### ISSUE TITLE
`pnpm create mastra` stuck at install step

### ISSUE THREAD

**Issue by stevenwu** [mastra-ai/mastra#1963]
`pnpm create mastra` gets stuck at
```
◐  Installing mastra..
```

I'm on node v23.7.0 if that matters.

**Comment by goszczynskip** [comment]
When using pnpm v10.4.1 with node 22.14.0, mastra installation stucks on building its dependencies

Log:
```
$ pnpm approve-builds 
✔ Choose which packages to build (Press <space> to select, <a> to toggle all, <i> to invert selection) · @swc/core, esbuild, mastra, protobufjs
✔ The next packages will now be built: @swc/core, esbuild, mastra, protobufjs.
Do you approve? (y/N) · true
node_modules/.pnpm/esbuild@0.25.0/node_modules/esbuild: Running postinstall script, done in 1.3s
node_modules/.pnpm/esbuild@0.24.2/node_modules/esbuild: Running postinstall script, done in 1.1s
node_modules/.pnpm/@swc+core@1.10.18/node_modules/@swc/core: Running postinstall script, done in 889ms
node_modules/.pnpm/protobufjs@7.4.0/node_modules/protobufjs: Running postinstall script, done in 443ms
node_modules/.pnpm/mastra@0.2.1_@opentelemetry+api@1.9.0_react@19.0.0/node_modules/mastra: Running postinstall script...
```

**Comment by wardpeet** [comment]
Could you let us know what operating system you're running?

**Comment by danielcspaiva** [comment]
I can confim I am facing the same issue while trying to start a project with pnpm or when trying to install dependencies with pnpm after starting a project with npm

**Comment by TylerBarnes** [comment]
This is fixed in `pnpm create mastra@0.1.3-alpha.0`. Should be fixed on latest shortly! Thanks everyone for the reports and helpful debug info

**Comment by TylerBarnes** [comment]
Also fixed on latest `pnpm create mastra@latest`. Closing this issue but if anyone's still experiencing problems on latest, drop a message here and I'll re-open

**Comment by danielcspaiva** [comment]
Hey @TylerBarnes, thank you for following up!

As of now I still can't make it work with pnpm, either pnpx or pnpm create. I can start a project just fine with npm:

<img width="445" alt="Image" src="https://github.com/user-attachments/assets/478a45bf-6b97-4a96-ba26-737cfc1212b2" />

**Comment by danielcspaiva** [comment]
The same with "pnpm create mastra@0.1.3-alpha.0":

<img width="399" alt="Image" src="https://github.com/user-attachments/assets/19679184-75ec-4333-b28e-5655e21ff491" />

**Comment by TylerBarnes** [comment]
@danielcspaiva does it work with `pnpm create mastra@0.1.3` ? If not do you have mastra cli installed globally? If you do what do you get when you run `mastra --version`?

**Comment by danielcspaiva** [comment]
@TylerBarnes no, it didn't work with "pnpm create mastra@0.1.3", it timed out.

I don't have the cli installed. I am running pnpm 9.15.0 and have no trouble starting other projects with pnpm.

<img width="558" alt="Image" src="https://github.com/user-attachments/assets/52a0de9d-b4f9-4baf-acbc-579caaee827b" />

**Comment by danielcspaiva** [comment]
It might be somehow related to this other issue: https://github.com/mastra-ai/mastra/issues/1991

I got the same error when starting a project with npx and then trying to install dependencies with pnpm.

**Comment by TylerBarnes** [comment]
@danielcspaiva thanks for that info and yes that seems likely to me as well. @TheIsrael1 is taking a look at that other issue right now so we can take another look soon once that's fixed

**Comment by TheIsrael1** [comment]
Yeah we have a change in main to attempt fixing #1991, we'll have an alpha version out in a bit to test.

**Comment by TheIsrael1** [comment]
This is now fixed on the latest alpha version with `pnpm create mastra@0.1.4-alpha.2`.  We'll cut a stable release soon too. Thanks all. 

Edit: Now Fixed in  new stable release `create-mastra@0.1.4`
