### ISSUE TITLE
`yarn create mastra` throws `Something went wrong` error

### ISSUE THREAD

**Issue by jayaramkasi** [mastra-ai/mastra#2013]
MacOSX Sequoia v15.3.1

 % yarn create mastra@latest
➤ YN0000: · Yarn 4.6.0
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + create-mastra@npm:0.1.3, @sec-ant/readable-stream@npm:0.4.1, @sindresorhus/merge-streams@npm:4.0.0, asynckit@npm:0.4.0, atomic-sleep@npm:1.0.0, axios@npm:1.7.9, and 75 more.
➤ YN0000: └ Completed in 0s 853ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 81 packages were added to the project (+ 14.49 MiB).
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: · Done with warnings in 0s 963ms

┌  Mastra Create
│
◇  What do you want to name your project?
│  test-mastra-app
│
◇  Project created
│
▲  Something went wrong

**Comment by abhiaiyer91** [comment]
Hi @jayaramkasi ! Thanks for reporting this! I did a sketchy deploy earlier this evening that I had a feeling would break yarn but now I know it definitely did! Sorry :( ! We're on it!!

**Comment by TheIsrael1** [comment]
Hi @jayaramkasi, we have deployed a fix for this and `yarn create mastra`  should now work with the latest stable release. Thanks for surfacing!

**Comment by jayaramkasi** [comment]
Actually it is still having the same issue 

yarn create mastra@latest       
➤ YN0000: · Yarn 4.6.0
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + create-mastra@npm:0.1.6, @sec-ant/readable-stream@npm:0.4.1, @sindresorhus/merge-streams@npm:4.0.0, asynckit@npm:0.4.0, atomic-sleep@npm:1.0.0, axios@npm:1.8.1, and 75 more.
➤ YN0000: └ Completed in 1s 531ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 81 packages were added to the project (+ 14.52 MiB).
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: · Done with warnings in 1s 659ms

┌  Mastra Create
│
◇  What do you want to name your project?
│  test-mastra-app
│
◇  Project created
│
▲  Something went wrong

Is there anything you recommend that I try?

**Comment by jayaramkasi** [comment]
pnpm and npx are all working fine though

**Comment by TheIsrael1** [comment]
There seems to be a bug with yarn having issues with resolving specific type of paths, in your case I belive adding the `@latest` tag messes up path resolution on installation

Here is a related issue
https://github.com/yarnpkg/yarn/issues/6851

just running `yarn create mastra` without the version tag seems to work though, we already recommend that in our docs, pls let me know if it works for you @jayaramkasi

**Comment by jayaramkasi** [comment]
Got it. I think the issue is possibly at yarn's end. I already tried `yarn create mastra` and it had the same issue. 

 yarn create mastra
➤ YN0000: · Yarn 4.6.0
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + create-mastra@npm:0.1.6, @sec-ant/readable-stream@npm:0.4.1, @sindresorhus/merge-streams@npm:4.0.0, and 78 more.
➤ YN0000: └ Completed in 0s 701ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 81 packages were added to the project (+ 14.52 MiB).
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: · Done with warnings in 0s 824ms

┌  Mastra Create
│
◇  What do you want to name your project?
│  code-reviewer-mastra
│
◇  Project created
│
▲  Something went wrong

**Comment by jayaramkasi** [comment]
tried `yarn cache clean` and re-running and still having the same issue. 

I'm okay as long as pnpm is working though :)

**Comment by TheIsrael1** [comment]
Ah on closer inspection, It also seems your'e using the modern versions of yarn (i see `4.6.0`), which i think  is meant to be used on a per project basis https://yarnpkg.com/getting-started/install. 

The community seems to still recommend using yarn classic as the global binary

**Comment by jayaramkasi** [comment]
yup this solves it. sorry :)
