### ISSUE TITLE
[BUG] CORS Issue with `mastra dev`: `Access-Control-Allow-Headers` incorrect in Preflight Response

### ISSUE THREAD

**Issue by sher1ock-jp** [mastra-ai/mastra#3339]
### Describe the Bug

When making API requests from a frontend application (e.g., running on `http://localhost:3000`) to the Mastra development server (`mastra dev`, typically on `http://localhost:4111`), a CORS policy error occurs in the browser.

The root cause appears to be that the preflight (`OPTIONS`) request sent by the browser does not receive a response with the necessary `x-mastra-client-type` header included in the `Access-Control-Allow-Headers` list. This header is automatically added by `@mastra/client-js`.

### Steps To Reproduce

1.  Set up a basic Mastra project with an agent or workflow.
2.  Run the Mastra development server using `mastra dev`.
3.  Set up a simple frontend application (e.g., using `fetch` in plain JS or a framework like React) on a different origin (e.g., `http://localhost:3000`).
4.  Use `@mastra/client-js` in the frontend to make a request to a Mastra API endpoint (e.g., `/api/workflows/welcomeWorkflow/createRun`).
5.  Observe the CORS error in the browser's developer console.
6.  Simulate the preflight request using `curl`:
    ```bash
    curl -X OPTIONS \
      -H "Origin: http://localhost:3000" \
      -H "Access-Control-Request-Method: POST" \
      -H "Access-Control-Request-Headers: x-mastra-client-type" \
      -v \
      http://localhost:4111/api/workflows/welcomeWorkflow/createRun
    ```

## Expected Behavior

The preflight (`OPTIONS`) response from the `mastra dev` server should include `x-mastra-client-type` (and potentially others like `x-mastra-cloud`, `x-mastra-dev-playground`) in the `Access-Control-Allow-Headers` response header, allowing the actual request from the frontend to proceed.

Example expected header:
`access-control-allow-headers: Content-Type, Authorization, x-mastra-client-type, ...`

## Actual Behavior

The preflight (`OPTIONS`) response from the `mastra dev` server consistently returns:

< access-control-allow-headers: Content-Type,Authorization >

This is missing the required `x-mastra-client-type` header, causing the browser to block the subsequent request due to CORS policy.

## Debugging Attempts & Findings

Multiple attempts were made to configure CORS correctly using the standard `serverMiddleware` option in `src/mastra/index.ts`, none of which affected the preflight response headers:

1.  **Custom CORS Middleware:** Added a custom Hono middleware explicitly setting `Access-Control-Allow-Headers` to include `x-mastra-client-type`. **Result:** No change in `curl -X OPTIONS` response.
2.  **Relying on Default CORS:** Removed all custom CORS middleware and set `serverMiddleware: []`, attempting to rely on the default `hono/cors` middleware supposedly configured within `@mastra/deployer`. **Result:** No change.
3.  **Direct `hono/cors` Usage:** Imported `cors` from `hono/cors` and used it directly as the first middleware in `serverMiddleware`, explicitly configuring `allowHeaders` to include `x-mastra-client-type`. **Result:** No change.
4.  **Debug Logging Middleware:** Added a logging middleware at the *very beginning* of the `serverMiddleware` array to log request/response details.
    *   **Finding 1:** Logs *did* appear for other requests (e.g., background refresh requests from the Mastra playground UI like `/refresh-events`), proving the `serverMiddleware` mechanism itself works.
    *   **Finding 2 (Key Finding):** Logs did **NOT** appear when sending the `curl -X OPTIONS ...` preflight simulation request.

## Conclusion / Hypothesis

The debugging steps, particularly the absence of debug logs for the `OPTIONS` request, strongly suggest that the `mastra dev` server (likely via `@mastra/deployer` or its underlying Hono setup) processes and responds to `OPTIONS` (preflight) requests **before** the user-defined `serverMiddleware` in `src/mastra/index.ts` is executed.

Therefore, any CORS configuration attempts within `serverMiddleware` have no effect on the actual preflight response sent back to the browser. The default `OPTIONS` handler within `mastra dev` seems to be returning an incomplete/incorrect `Access-Control-Allow-Headers` list.

## Environment

*   Mastra project running via `mastra dev`
*   Frontend using `@mastra/client-js`

### Component

Workflows

### Code Snippet

```typescript

```

### Error Logs

```shell

```

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

**Comment by abhiaiyer91** [comment]
Hi @sher1ock-jp thank you so much for reporting this. We got several reports in discord as well and are fixing it! cc @TheIsrael1

**Comment by hieuminh65** [comment]
have this as well, I wonder why I do not update my dependency but why still have this problem. Do anyone know this?

**Comment by TheIsrael1** [comment]
Hi @hieuminh65 This should be fixed on the latest version now, kindly update to the latest version of mastra `mastra@latest`

**Comment by hieuminh65** [comment]
I still got the same issue:
- "mastra": "^0.4.4",
- "@mastra/client-js": "^0.1.13",
- "@mastra/core": "^0.7.0"

**Comment by TheIsrael1** [comment]
Hi @sher1ock-jp @hieuminh65 my bad, this is fixed in our alpha version `mastra@alpha`, we've have not cut a stable release yet.

**Comment by wardpeet** [comment]
Going to close this as fixed in @alpha, please re-open if this was a mistake or still broken

**Comment by hieuminh65** [comment]
Hello @wardpeet , @TheIsrael1 
## The error still happens when I deploy to vercel. It works fine locally.
<img width="876" alt="Image" src="https://github.com/user-attachments/assets/43ac5e79-77f0-4751-b068-042f59293127" />

## Versions
- @mastra/client-js": "^0.1.14-alpha.5",
- @mastra/core": "^0.8.0-alpha.5",
- @mastra/deployer-vercel": "^0.1.15-alpha.8",


## Code
```typescript
import { Mastra } from "@mastra/core";
import { VercelDeployer } from "@mastra/deployer-vercel";

export const mastra = new Mastra({
  deployer: new VercelDeployer({
    teamSlug: "xxx",
    projectName: "xx-mastra",
    token: process.env.VERCEL_TOKEN || "",
  }),
  ...
});

**Comment by kuski2** [comment]
The problem is still occurring on vercel

## Versions

- "@mastra/core": "^0.9.1",
- "@mastra/deployer-vercel": "^0.1.20",
- "@mastra/client-js": "^0.1.19",
