### ISSUE TITLE
[BUG] SyntaxError: The requested module './telemetry-config.mjs' does not provide an export named 'telemetry' with @mastra/core@0.9.0

### ISSUE THREAD

**Issue by federiconeri** [mastra-ai/mastra#4362]
### Describe the Bug

When deploying a Mastra application (using `@mastra/core@0.9.0` and `@mastra/pg@0.3.0`) to Mastra Cloud, the deployment consistently fails during the "Checking readiness..." phase. The error occurs in a Mastra Cloud generated file (`/data/project/apps/api/.mastra/output/instrumentation.mjs`) which attempts to import a `telemetry` object from `./telemetry-config.mjs`, but this export is not found.

This issue persists despite various attempts to configure or disable telemetry in the `mastra-config.ts` file and via environment variables in Mastra Cloud. The project is pinned to `@mastra/core@0.9.0` due to a separate Bun compatibility issue (HTTPParser error, similar to Mastra GitHub issue #4264).

The Mastra Cloud deployment logs indicate it's using `deployer core-0.9.0`. A similar issue (same error message and context) is reported in Mastra GitHub issue #4142.

__Actual Behavior:__ The deployment process installs dependencies and builds the application, but fails at the "Checking readiness..." step with the following log:

```javascript
[INFO] ... Checking readiness...
[INFO] ... file:///data/project/apps/api/.mastra/output/instrumentation.mjs:3
import { telemetry } from './telemetry-config.mjs';
         ^^^^^^^^^
SyntaxError: The requested module './telemetry-config.mjs' does not provide an export named 'telemetry'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:182:21)
    ...
Node.js v22.15.1
[INFO] ... Readiness probe attempt 1/5
[ERROR] ... Probe attempt failed: fetch failed
...
[ERROR] ... Readiness probe failed
```

__Additional Context:__ The project is pinned to `@mastra/core@0.9.0` because newer versions encountered an `HTTPParser` error with Bun (similar to Mastra GitHub issue #4264). This prevents upgrading Mastra as a simple fix. The core issue seems to be that `deployer core-0.9.0` unconditionally expects a valid `telemetry` export from its internally generated `telemetry-config.mjs`.

### Steps To Reproduce

- __Project Setup:__

  - Create a Mastra application using `@mastra/core@0.9.0`.
  - Ensure the `mastra` instance is exported as a named export from the entry point specified as "Mastra Directory" (e.g., `apps/api/src/ai-crew/index.ts` exports `mastra` from `apps/api/src/ai-crew/config/mastra-config.ts`).
  - The project uses Bun and `bun.lockb`.

- __Mastra Cloud Configuration:__

  - Set "Project root" to `./apps/api`.

  - Set "Mastra Directory" to `src/ai-crew`.

  - Set "Build Command" to:

    ```bash
    apt-get update && apt-get install -y unzip && curl -fsSL https://bun.sh/install | bash && export PATH="/root/.bun/bin:$PATH" && bun install && bun run build
    ```

- __Telemetry Configurations Attempted (all lead to the same error):__

  - No `telemetry` block in `Mastra` constructor in `mastra-config.ts`.
  - `telemetry: { enabled: false, serviceName: 'my-app' }` in `mastra-config.ts`.
  - Full `telemetry` block with `enabled: true`, `MastraCloudExporter` (from `@mastra/cloud@0.0.3`), and `process.env.MASTRA_CLOUD_ACCESS_TOKEN` (with a placeholder value set for the ENV VAR in Mastra Cloud).
  - Setting environment variable `MASTRA_TELEMETRY_DISABLED=1` in Mastra Cloud project settings.

- __Trigger Deployment:__ Push changes to the linked GitHub repository.

### Expected Behavior

The application should deploy successfully. If telemetry is disabled or not fully configured (e.g. missing an optional access token for a cloud exporter when `enabled: false`), the telemetry instrumentation should be gracefully skipped or handled without causing a fatal `SyntaxError`.

### Environment Information

- `@mastra/core`: `0.9.0`

- `@mastra/pg`: `0.3.0`

- `@mastra/cloud` (dependency, added during troubleshooting): `0.0.3`

- Deployment Platform: Mastra Cloud

- Mastra Cloud Deployer Version (from logs): `core-0.9.0`

- Runtime Environment for Build on Mastra Cloud: Debian Bookworm (Node.js v22.15.1, Bun v1.2.13 installed via build script)

- Project Structure: Monorepo using Bun workspaces.

  - Mastra Cloud "Project root": `./apps/api`
  - Mastra Cloud "Mastra Directory": `src/ai-crew` (This is where the `Mastra` instance is configured and exported)

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

**Comment by abhiaiyer91** [comment]
Hi @federiconeri , we made some changes here and now are in the 0.10.x era of mastra. Does this still reproduce there?

**Comment by artsparkAI** [comment]
Hello @abhiaiyer91 @federiconeri  I believe I found a clue to the issue.
If you comment out [`import { deepMerge } from '@mastra/core';`](https://github.com/mastra-ai/mastra/blob/c5bf1ce8af0043d1866e42cdab874d0980b1575a/packages/memory/src/index.ts#L1) and just inline the function instead, it seems to work.

It appears that something imported in [utils.ts](https://github.com/mastra-ai/mastra/blob/c5bf1ce8af0043d1866e42cdab874d0980b1575a/packages/core/src/utils.ts#L21) causes the issues

#4084 #4264

**Comment by wardpeet** [comment]
Pretty sure this is fixed in 0.10.0, but failing for bun. We need to wait for https://github.com/mastra-ai/mastra/issues/4084

**Comment by federiconeri** [comment]
Thanks a lot @wardpeet @abhiaiyer91 @artsparkAI. Due to these issues, we've temporarily put our migration to Mastra on hold, but we're planning to get back to it in the next few weeks as soon as we release our product. I'll try what you suggested and keep you posted.

**Comment by dcramer** [comment]
FYI still seeing this in latest

```
    "@mastra/core": "^0.10.5",
    "@mastra/libsql": "^0.10.2",
    "@mastra/loggers": "^0.10.2",
    "@mastra/memory": "^0.10.3",
```

Got here via Google, but current open ticket is #4822

**Comment by kumarabhirup** [comment]
Seeing this in latest.
```
    "@mastra/auth": "^0.1.3",
    "@mastra/client-js": "^0.13.1",
    "@mastra/core": "^0.17.0",
    "@mastra/deployer": "^0.17.0",
    "@mastra/inngest": "^0.14.0",
    "@mastra/libsql": "^0.14.2",
    "@mastra/loggers": "^0.10.12",
    "@mastra/memory": "^0.15.2",
```

Mastra Cloud Deployment
```
[INFO]
[10/03/2025, 03:29:03 PM] - Readiness probe attempt 3/5
[ERROR]
[10/03/2025, 03:29:03 PM] - Probe attempt failed: fetch failed
[INFO]
[10/03/2025, 03:29:03 PM] - Retrying in 16.1 seconds...
[INFO]
[10/03/2025, 03:29:19 PM] - Readiness probe attempt 4/5
[ERROR]
[10/03/2025, 03:29:19 PM] - Probe attempt failed: fetch failed
[INFO]
[10/03/2025, 03:29:19 PM] - Retrying in 15.6 seconds...
[INFO]
[10/03/2025, 03:29:34 PM] - Readiness probe attempt 5/5
[ERROR]
[10/03/2025, 03:29:34 PM] - Probe attempt failed: fetch failed
[INFO]
[10/03/2025, 03:29:35 PM] - Readiness probe failed due to timeout
[ERROR]
[10/03/2025, 03:29:35 PM] - Build process failed for build 14ac3392-6f3c-4751-a47d-dd0ecaf733f8 and project 98f828f3-6977-4762-b990-1abf5ab9dab8: {"message":"Unknown error","details":{"message":"Unknown error","domain":"BUILDER","category":"SYSTEM","details":{}},"code":"READINESS_PROBE_ATTEMPTS_EXCEEDED"}
[ERROR]
[10/03/2025, 03:29:35 PM] - Unknown error
```

**Comment by mwood23** [comment]
```
"@mastra/cloudflare-d1": "0.13.7",
"@mastra/core": "0.23.1",
"@mastra/langfuse": "0.2.1",
"@mastra/libsql": "0.16.1",
"mastra": "0.17.5",
```

<img width="812" height="360" alt="Image" src="https://github.com/user-attachments/assets/2c62f0c2-cedc-4340-86d2-10fe0a888c64" />

still seeing this fwiw

**Comment by mwood23** [comment]
Ohhhhh, trippy. My code had this...

Broken:
```ts
export const mastra = createMastra();
export default mastra;
```

Works:
```ts
export const mastra = createMastra();
```

I feel like this should toss an exception if default exports won't work.

**Comment by wardpeet** [comment]
We might have fixed this or at least i'm pretty sure we are throwing an error on latest

**Comment by mwood23** [comment]
I think I'm on the latest (`0.17.5`)?  https://www.npmjs.com/package/mastra?activeTab=versions
