### ISSUE TITLE
[BUG] Deployers (Vercel, Netlify)

### ISSUE THREAD

**Issue by PaulieScanlon** [mastra-ai/mastra#5137]
### Describe the Bug

When using git push / CI workflows neither the Vercel or Netlify Deployers deploy Mastra correctly. 
My tests produce the following:

## Vercel
 - Repo: https://github.com/PaulieScanlon/_test-standalone-vercel
 - Preview: https://test-standalone-vercel.vercel.app/
 
## Netlify
- Repo: https://github.com/PaulieScanlon/_test-standalone-netlify
- Preview: https://test-standalone-netlify.netlify.app/

## Cloudflare
I haven't tested Cloudflare yet

For Vercel and Netlify, following the docs, and running a build locally, then using one of the following to manulaly deploy works fine:
- Vercel: `cd .mastra/output` | `vercel --prod`
- Netlify `cd .mastra/output` | `netlify deploy --prod --dir . --functions ./netlify/functions`

The build output settings appear to be correct as you'll notice from the above preview links, Mastra code is being deployed. 

It appears this issue is related to CI / git push pipeline.

Not fully tested this, but CI / git push pipelines will likely also affect monorepo setups as the Mastra setup will be the same as it is for standalone Mastra setups. 

### Steps To Reproduce

This issue exists with projects created using `create-mastra` and when adding either the Vercel or NetlifyDeployers. In both above cases, the remaining settings for the Deployer oject were correct and relevant "token" keys were added to both Vercel and Netlify. 

### Expected Behavior

After using git push, the deployed Mastra instance should display the "Welcome to Mastra" page as it does when manually deploying. 

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

**Comment by TheIsrael1** [comment]
Hi @PaulieScanlon For the Netlify deployer, I've updated the docs for dashboard deployments.
Because of how netlify resolves path, The build settings need to be configured as explained in this PR
https://github.com/mastra-ai/mastra/pull/5178

**Comment by alizenhom** [comment]
@TheIsrael1 
I am having the exact issue with vercelDeployer, when following the docs and manually 
- cd `./mastra/output` 
- run `vercel --prod`

it works fine, but when i add this to a pipeline using vercel APIs, it actually returns the whole compiled javascript

**Comment by PaulieScanlon** [comment]
Thanks @TheIsrael1, confirmed. With the correct publish, and functions set in the Netlify Dashboard, this now works.

I'm still experiencing issues with the `VercelDeployer` though. Will this go out as part of the release tomorrow?

**Comment by PaulieScanlon** [comment]
Hey @alizenhom, this is now fixed, and we have new docs to help you on your way: https://mastra.ai/en/docs/deployment/serverless-platforms/vercel-deployer
