### ISSUE TITLE
Monorepos Support mega issue

### ISSUE THREAD

**Issue by LekoArts** [mastra-ai/mastra#6852]
# Mastra 🤝🏻 Monorepos

Hello everyone! 👋🏻

We love to see how many of you want to use Mastra. A lot of you are using Mastra as part of their monorepo setup, often authored in TypeScript. We hear you loud and clear (e.g. through issue like [#1996](https://github.com/mastra-ai/mastra/issues/1996)) that there are currently pain points when trying to use TypeScript monorepos with Mastra.

The gist of it is that Mastra currently doesn't support parsing TypeScript files by default. You either have to add a build step to your packages, compiling them to JavaScript or use the `transpilePackages` option.

**This is where you come in!**

To be able to _make moves_ and fix these issues, we need a more structured approach to tackling them. In various GitHub issues people mentioned multiple, distinct setups and their respective bugs. There doesn't seem to be _one_ single issue or setup that doesn't work.

Therefore we'd like to ask you to:

**Send in your minimal reproductions of your bugs with Mastra + TypeScript monorepos.** This is a smaller, simplified Mastra project that demonstrates your issue. Having a working reproduction in a new project helps to confirm that this is a repeatable problem, and is not caused by something else in your personal environment or existing project.

## How to create a minimal reproduction

1. Setup your project
	- Follow [Mastra's install instructions](https://mastra.ai/en/docs/getting-started/installation) and add your monorepo setup
	- Alternatively, you can fork [this example project](https://github.com/lekoarts-demos/mastra-monorepo-01) and try to reproduce your issue there
3. Verify that your minimal reproduction shows your issue
4. Share the link to the public GitHub repository in this issue
5. Write down the clear reproduction steps (e.g. "Run `mastra dev` to see this error x")

> [!TIP]
> Use the `@alpha` version of Mastra packages to receive the latest published version from our `main` branch. This way you can quickly test out bug fixes we ship.

If you can't / don't want to create a minimal reproduction but have an existing project showing a bug, we can take a look at it if:
- We can run the project without us requiring to add environment variables or having access to private npm packages
- It's a public GitHub repository

We prefer not to look at your private company project as that can come with legal headaches.

## Our game plan

With the help of your reproductions we want to squash more of these monorepo bugs. By working through them we should also be able to see if our documentation needs updates (e.g. specific instructions for how to setup a monorepo that works with Mastra) or if we wan fix it all in code.

You'll be able to test out updates for this regularly by installing the `@alpha` version.

## Related issues

https://github.com/mastra-ai/mastra/issues/1996
https://github.com/mastra-ai/mastra/issues/6213
https://github.com/mastra-ai/mastra/issues/6216

If you have opened an issue/Discord thread in the past that is related and not listed here, please comment, too.

**Comment by xpender** [comment]
Hello,

thanks for caring about that topic.

We have an issue with packages marked as `externals` - you can find a repository where this error is reproducible at https://github.com/xpender/mastra-monorepo-01/tree/main

The error is reproducible with:
```bash
git clone https://github.com/xpender/mastra-monorepo-01.git
pnpm i
pnpm build
```
(See also the README for additional information: https://github.com/xpender/mastra-monorepo-01/blob/main/README.md#wip)

**Comment by wardpeet** [comment]
Thanks for the reproduction! Adding 
```
  "exports": {
    ".": {
      "types": "./src/index.ts",
      "import": "./dist/index.js",
      "default": "./dist/index.js"
    },
    "./package.json": "./package.json"
  },
```
To your package.json fixes it, will add a hotfix

**Comment by wardpeet** [comment]
Fixed by https://github.com/mastra-ai/mastra/pull/6883

**Comment by andrueandersoncs** [comment]
Here's our reproduction with our bun monorepo. Getting a simple "cannot find module" error.
https://github.com/andrueandersoncs/mastra-monorepo-reproduction

**Comment by tomaswitek** [comment]
Hey @wardpeet here is my monorepo with a small issue: https://github.com/tomaswitek/mastra-monorepo
I get a compilation error when running `dev` script:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ragie' imported from /Users/tom/code/mastra-monorepo/apps/mastra/.mastra/output/index.mjs
Did you mean to import "ragie/index.js"?
```
Can you please have a look when you have time?
More details are in the repo readme.

Otherwise great work on the monorepo issue 🙏  
Thank you very much!

**Comment by TheIsrael1** [comment]
Hi @andrueandersoncs Your reproduction seems to now be fixed with latest `mastra`. I made a PR https://github.com/andrueandersoncs/mastra-monorepo-reproduction/pull/1

**Comment by TheIsrael1** [comment]
> Hey [@wardpeet](https://github.com/wardpeet) here is my monorepo with a small issue: [tomaswitek/mastra-monorepo](https://github.com/tomaswitek/mastra-monorepo?rgh-link-date=2025-08-23T19%3A19%3A53.000Z) I get a compilation error when running `dev` script:
> 
> ```
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ragie' imported from /Users/tom/code/mastra-monorepo/apps/mastra/.mastra/output/index.mjs
> Did you mean to import "ragie/index.js"?
> ```
> 
> Can you please have a look when you have time? More details are in the repo readme.
> 
> Otherwise great work on the monorepo issue 🙏 Thank you very much!

Hi @tomaswitek I am unable to reproduce the issue in both apps in your monorepo. The dev script starts successfully for both.

**Comment by sbue** [comment]
Here's another repo where you can reproduce the issue: https://github.com/segundo-ai/mastra-monorepo-fail

**Comment by thereis** [comment]
Should we transpile the TypeScript files in our project to JavaScript so they can be imported correctly? Looking forward for these fixes in a setup using Turborepo! 😄

**Comment by tomaswitek** [comment]
> > Hey [@wardpeet](https://github.com/wardpeet) here is my monorepo with a small issue: [tomaswitek/mastra-monorepo](https://github.com/tomaswitek/mastra-monorepo?rgh-link-date=2025-08-23T19%3A19%3A53.000Z) I get a compilation error when running `dev` script:
> > ```
> > Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ragie' imported from /Users/tom/code/mastra-monorepo/apps/mastra/.mastra/output/index.mjs
> > Did you mean to import "ragie/index.js"?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can you please have a look when you have time? More details are in the repo readme.
> > Otherwise great work on the monorepo issue 🙏 Thank you very much!
> 
> Hi [@tomaswitek](https://github.com/tomaswitek) I am unable to reproduce the issue in both apps in your monorepo. The dev script starts successfully for both.

Hey @TheIsrael1 you are right. Can you please try again now I had a different code in the repo :D

**Comment by jhleao** [comment]
Here goes another minimal issue reproduction. This is potentially another example of the issue @tomaswitek is facing. In my case, the problematic peer dependency is `dayjs`.

https://github.com/jhleao/mastra-monorepo

**Comment by LekoArts** [comment]
@jhleao @tomaswitek Thanks for the repositories, appreciate it. You're seeing problems with `mastra dev` because currently it functions differently than `mastra build`. This was done (in the past) to save on startup time for `mastra dev`.

When you run `mastra build` for your projects you'll see that it works. Of course, it should function in both cases! For now, you can workaround it by adding the dependency to the project that contains Mastra.

---

@tomaswitek As to your questions: You won't need to define peerDependencies. And `transpilePackages` doesn't support wildcards on purpose.

---

@thereis Have you tried the `transpilePackages` option? If that doesn't work, can you please provide a minimal reproduction as explained in the first post? Thanks!

---

@sbue Thanks for the repository. I'm afraid you're using a pattern that we can't support. You'll need to change your `apps/web/src/mastra/index.ts` file to the following:

```ts
import { Mastra } from '@mastra/core/mastra'
import { weatherAgent } from '@segundo/api/mastra/agents/weather-agent'

export const mastra = new Mastra({
  agents: {
    weatherAgent,
  },
  bundler: {
    transpilePackages: ['@segundo/api']
  }
})
```

We need to be able to parse the Mastra configuration and you can't put the Mastra configuration into a package that is inside `transpilePackages`.

**Comment by thereis** [comment]
@LekoArts I have a project configured in a very similar way that @jhleao provided, using pnpm workspaces + turborepo for monorepo management. I think if his problem gets sorted, mine will also be sorted ;) 

Waiting anxiously for this to get sorted out soon 😄

**Comment by tomaswitek** [comment]
Thx @LekoArts ok I get it now. So currently the sub dependencies from packages will run ok while running build script but for dev you have to add them in the main app.
A few followup questions:
1. Do you plan to adjust the dev script so we don't have to define deps in the main app?
2. Are you open for a PR? I'll help you guys if needed.
3. Hot reload currently seems to be broken. When I do a change in packages I have to restart the mastra dev server. Is that by design?

Thx again for your work and time. As I mentioned I am ready to invest my time and help you guys.

**Comment by LekoArts** [comment]
@tomaswitek Thanks for the kind offer, appreciate it. We'll work on the PRs to make things happen but I'd be happy to have you test things out once they are in.

Regarding your questions:
- `mastra dev` and `mastra build` should behave the same in the future so yes, you won't need to define the deps
- I'm not sure myself yet if we want to support that type of hot-reloading (as I don't know how involved that is). I can get back to you about that at a later point once we fixed the more critical bugs 😊

**Comment by qantrepreneur** [comment]
Hello! I was just wondering if there's any ETA on this? Very excited to use Mastra.

**Comment by wardpeet** [comment]
We made a lot of progress today on trying to come up with solutions for these things. ETA is probably going to be on Monday having an alpha and tuesday having it in latest. If we are not confident we might push it for the week after

**Comment by flippyhead** [comment]
Not sure if this helps,but upated to latest alpha and on mastra dev, still getting this kind of error:

```◐ Preparing development environment...
✓ Initial bundle complete
◇ Starting Mastra dev server...
(node:87636) ExperimentalWarning: Type Stripping is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

node:internal/modules/run_main:104
    triggerUncaughtException(
    ^
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/Users/peterbrown/Development/already-app/packages/database/src/db' is not supported resolving ES modules imported from /Users/peterbrown/Development/already-app/packages/database/src/db/concepts/service.ts
    at finalizeResolution (node:internal/modules/esm/resolve:263:11)
    at moduleResolve (node:internal/modules/esm/resolve:860:10)
    at defaultResolve (node:internal/modules/esm/resolve:984:11)
    at nextResolve (node:internal/modules/esm/hooks:748:28)
    at resolve (file:///Users/peterbrown/Development/already-app/node_modules/.pnpm/mastra@0.12.0_@mastra+core@0.16.0_openapi-types@12.1.3_react@19.1.1_zod@3.25.76__@opentelemet_7qolmohwxojuy3qjvzvevwedra/node_modules/mastra/dist/commands/dev/telemetry-resolver.js:4:12)
    at nextResolve (node:internal/modules/esm/hooks:748:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:240:30)
    at handleMessage (node:internal/modules/esm/worker:199:24)
    at Immediate.checkForMessages (node:internal/modules/esm/worker:141:28)
    at process.processImmediate (node:internal/timers:508:21) {
  code: 'ERR_UNSUPPORTED_DIR_IMPORT',
  url: 'file:///Users/peterbrown/Development/already-app/packages/database/src/db'
}
```

**Comment by LekoArts** [comment]
@flippyhead Please follow the "How to create a minimal reproduction" section in the first post and link to your repository that shows this error. Thanks!

**Comment by LekoArts** [comment]
@tomaswitek @thereis @jhleao Please try the latest `alpha` versions of all Mastra packages (e.g. `@mastra/core 0.16.1-alpha.0`). I merged a PR and have seen success with your reproductions. (https://github.com/mastra-ai/mastra/pull/7572)

**Comment by cian** [comment]
Unfortunately I've seen a regression today in alpha.
Please ignore the confusing repo name, but you'll see that `pnpm dev` works here: https://github.com/cian/mastra-monorepo-yarn-example/tree/cian/no-barrel
But fails here: https://github.com/cian/mastra-monorepo-yarn-example/tree/cian/no-barrel-alpha

In the failing version, I can see it's outputting all the necessary .mjs files, but they're landing outside of `.mastra`.

As a second-order issue, it would be nice to be able to write:
```
  bundler: {
    transpilePackages: ['@monorepo/bar']
  }
```
instead of:
```
  bundler: {
    transpilePackages: ['@monorepo/bar', '@monorepo/bar/otherthing']
  }
```
Since `@monorepo/bar/otherthing` isn't really a package.

However the main thing I wanted to call out in this repro example is the regression we're seeing today in alpha.

Thanks again for all your hard work in finding a stable way forward here, it's much appreciated.

**Comment by tomaswitek** [comment]
> [@flippyhead](https://github.com/flippyhead) Please follow the "How to create a minimal reproduction" section in the first post and link to your repository that shows this error. Thanks!

Hey @LekoArts thx for the new version, unfortunately my issue wasn't resolve I still see the same error in my monorepo:
```
node:internal/modules/run_main:104
    triggerUncaughtException(
    ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ragie' imported from /Users/tom/code/mastra-monorepo/apps/mastra/.mastra/output/index.mjs
Did you mean to import "ragie/index.js"?
```
What exactly should be better now?

I tested with @mastra/core v 0.16.2:

<img width="1487" height="105" alt="Image" src="https://github.com/user-attachments/assets/2a44fd47-4fab-4912-aa2d-e8e9f91de32d" />

**Comment by cian** [comment]
Just to update that we're unfortunately now seeing this issue it `latest` also since the 2025-09-10 release. It seems like https://github.com/mastra-ai/mastra/pull/7572 is what's causing this.

Is there an alternative way we should be structuring a bare monorepo (i.e. no roll-up index.ts file) so that it can be transpiled correctly? If not, and if this should be a supported configuration, then I'm happy to have a go at a fix.

UPDATE: If I work off the assumption that `transpilePackages` is really scoped to entrypoints rather than packages, then I can restore the old behavior by adding this to `watcher.ts`:
```
      let isWorkspace = workspaceMap.has(pkg);
      if (isWorkspace === false) {
        //Check if pkg is a submodule of a workspace package
        //This will extract foo from 'foo/bar/baz' and
        //'@mono/foo' from '@mono/foo/bar/baz'.
        const matchBase = RegExp(`((@[^/]*/)?[^/]*).+`)
        const o = pkg.match(matchBase);
        console.log("cianh: got o: ", o , " for: ", pkg);
        if (o && o[1]) {
          const baseMap = workspaceMap.get(o[1]);
          if (baseMap != undefined) {
            console.log ("found basemap, using for: ", pkg)
            workspaceMap.set(pkg, baseMap);
            isWorkspace = true;
          }
        }
      }
```

However, I'm still wondering what the expected behavior is, so I've still held off on proposing a fix.

Thanks!

> Unfortunately I've seen a regression today in alpha. Please ignore the confusing repo name, but you'll see that `pnpm dev` works here: https://github.com/cian/mastra-monorepo-yarn-example/tree/cian/no-barrel But fails here: https://github.com/cian/mastra-monorepo-yarn-example/tree/cian/no-barrel-alpha
> 
> In the failing version, I can see it's outputting all the necessary .mjs files, but they're landing outside of `.mastra`.
> 
> As a second-order issue, it would be nice to be able to write:
> 
> ```
>   bundler: {
>     transpilePackages: ['@monorepo/bar']
>   }
> ```
> 
> instead of:
> 
> ```
>   bundler: {
>     transpilePackages: ['@monorepo/bar', '@monorepo/bar/otherthing']
>   }
> ```
> 
> Since `@monorepo/bar/otherthing` isn't really a package.
> 
> However the main thing I wanted to call out in this repro example is the regression we're seeing today in alpha.
> 
> Thanks again for all your hard work in finding a stable way forward here, it's much appreciated.

**Comment by LekoArts** [comment]
Hello everyone, after lots of work we merged https://github.com/mastra-ai/mastra/pull/7619 and you can already try it on `@alpha`.

With this PR you'll no longer need to manually define the `transpilePackages` option, we autodiscover your workspaces packages now. You can still manually add entries there if you have other packages though.

I tested the PR with all reproductions and `mastra dev` & `mastra build` worked for me. We do know that there are still some bugs with `mastra build` + `mastra start` and with nested, transitive dependencies. We'll tackle these in other PRs.

@tomaswitek @thereis @jhleao please try again, since I tested the PR with your reproductions.

Thanks for helping! 🫶

**Comment by thereis** [comment]
Hey @LekoArts! I've set the channels to alpha, and the issue persists. Here is the fork from jhleao:

https://github.com/thereis/mastra-monorepo-issue

Is there any way that we could have a better logging or a stack trace for the issue? Even adding the package to the bundler options, the issue persisted.

```
◐ Preparing development environment...
✓ Initial bundle complete
◇ Starting Mastra dev server...

node:internal/modules/run_main:123
    triggerUncaughtException(
    ^
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for C:\Projetos\mastra-monorepo-issue\packages\ai-tools\src\index.ts
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:219:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:245:36)
    at defaultLoad (node:internal/modules/esm/load:120:22)
    at async nextLoad (node:internal/modules/esm/hooks:748:22)
    at async Hooks.load (node:internal/modules/esm/hooks:385:20)
    at async handleMessage (node:internal/modules/esm/worker:199:18) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

Node.js v22.17.1
```

Node: v22.17.1
pnpm: 10.15.0
OS: Windows 11

**Comment by LekoArts** [comment]
@thereis I can't reproduce this on my Mac, maybe your issue now is specific to Windows. Need to setup my Windows PC then...

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/13ff6bc9-118c-4729-8435-84796ae7c66b" />

There's no stack trace or anything for that, but you can look into the marked folders what get's created:

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/1108e2db-bb7f-4e31-aeab-d55de5cd9622" />

Does it have malformed strings?

Beyond that it's a matter of adding `debugger` or console.log to the `@mastra/deployer` source code and trying again and again.

**Comment by thereis** [comment]
@LekoArts, sadly those folders are empty :( I will try again tomorrow on my Mac to see if I can reproduce the error, but it's most likely that it's a Windows issue.

<img width="584" height="587" alt="Image" src="https://github.com/user-attachments/assets/e87c750d-ba45-4b57-b6ea-7d8bf0e3ae71" />

<img width="571" height="642" alt="Image" src="https://github.com/user-attachments/assets/a8e902e1-e044-4d1b-9a6f-811d81119539" />

**Comment by LekoArts** [comment]
I can reproduce your issue on my Windows machine 👍

**Comment by cian** [comment]
@LekoArts thank you for the fantastic work you've done to improve this support, your latest PR solves 95% of our issues, and we do have a working way forward for now by adding rollup `index.ts` files that export the dependencies required by Mastra at the root level of our shared packages.

This repo, shows the issue that persists when we don't have an `index.ts`: https://github.com/cian/mastra-monorepo-repro

The error we see is:
`ERROR [2025-09-17 09:22:24.760 +0100] (Mastra CLI): Could not load /Users/cian/Code/mastra-monorepo-repro/packages/shared/src/index.ts (imported by virtual:#virtual-@acme/shared): ENOENT: no such file or directory, open '/Users/cian/Code/mastra-monorepo-repro/packages/shared/src/index.ts'`

If I add an empty `index.ts`, this changes to:
`ERROR [2025-09-17 09:29:44.399 +0100] (Mastra CLI): ../../packages/shared/src/time.ts (3:5): Expected ';', '}' or <eof> (Note that you need plugins to import files that are not JavaScript)`

If I add back the original `index.ts` and the corresponding export in `package.json`, but *keep* the deep import `import { AcmeTime } from '@acme/shared/time';` in `packages/ai-tools/src/tools/weather-tool.ts` then `packages/shared/node_modules/.cache/@acme-shared-time.mjs` does get correctly generated, and everything works as expected (albeit with the `index.ts` and export that we'd rather not keep around).

### Potentially useful background:
In general, in our monorepo we follow the approach advocated for [https://tkdodo.eu/blog/please-stop-using-barrel-files](here) and [https://tkdodo.eu/blog/please-stop-using-barrel-files](here). We don't normally have `index.ts` files within the packages in our monorepo, our packages export typescript and we use deep imports within our Next.js apps and have Next take care of compiling our shared packages.

I'll have a shot at diving into the latest release to see if I can understand the underlying issue better, but wanted to share the reproduction with you in case it was an obvious fix on your end. Hopefully this sort of bare monorepo structure is something you'd like to support, but if not and this reproduction is just annoying noise let me know and we'll find a different path forward.

Thanks again!

ADDENDUM: I've also posted another minimal example of working around this here: https://github.com/cian/mastra-monorepo-repro/compare/main...cian:mastra-monorepo-repro:cian/workaround1?expand=1 - by manually specifying the deep import within transpilePackages, and manually adding it's dependency `dayjs` as a direct dependency of the model server.

**Comment by thereis** [comment]
Hey @LekoArts is there anything that I could help with the Windows issue?! Looking forward to it!

**Comment by LekoArts** [comment]
@thereis Thanks for your patience 👍  I was traveling and then sick but we just merged https://github.com/mastra-ai/mastra/pull/7943 and published it to `alpha`. So you could try it again.

@cian We'll give it a look 👍 

Currently we need to split our attention as there were some bug reports of people not using workspaces running into problems with our bundler changes (to cater for workspaces support). So we'll prioritize these bug reports over more niche use-cases of monorepos for now.

**Comment by thereis** [comment]
Hey @LekoArts thanks for the update! It looks like the bundler issue got solved but now I am facing a different issue 😄 

pnpm: 10.8.0
node: v22.17.1

Windows 11.


```bash
◐ Preparing development environment...
✓ Initial bundle complete
◇ Starting Mastra dev server...
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at target._send (node:internal/child_process:877:20)
    at target.send (node:internal/child_process:751:19)
    at file:///C:/Projetos/mastra-monorepo-issue/apps/myapp/.mastra/output/index.mjs:46323:17
    at Server.<anonymous> (file:///C:/Projetos/mastra-monorepo-issue/apps/myapp/.mastra/output/index.mjs:34794:26)
    at Object.onceWrapper (node:events:632:28)
    at Server.emit (node:events:530:35)
    at emitListeningNT (node:net:1983:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:89:21)
Emitted 'error' event on process instance at:
    at node:internal/child_process:881:39
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11) {
  errno: -4047,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v22.17.1
```

I also tried running the `build` and then `start`, and I got the previous error when bundling deps:

```bash
node:internal/modules/esm/get_format:219
  throw new ERR_UNKNOWN_FILE_EXTENSION(ext, filepath);
        ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for C:\Projetos\mastra-monorepo-issue\apps\myapp\.mastra\output\node_modules\.pnpm\@acme+ai-tools@file+workspa_593256b453076b7bb593e084d4c3aa2a\node_modules\@acme\ai-tools\src\index.ts
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:219:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:245:36)
    at defaultLoad (node:internal/modules/esm/load:120:22)
    at async ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:580:32) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

**Comment by wardpeet** [comment]
@cian https://github.com/mastra-ai/mastra/pull/8353 should fix your problem. Thank you for the reproduction.

**Comment by AarooneyFarr** [comment]
Hey guys,

I have been having a very similar issue to the one described by @cian 3 weeks ago. I have not had the time to make a minimal reproduction, but I can if it would be helpful. Here is my error message:

```
Mastra Build failed
    error: {
      "message": "Failed to analyze Mastra application: \u0000virtual:#virtual-@intervalai/sb (1:9): \"CustomerDao\" is not exported by \"../../packages/supabaseDAO/dist/index.js\", imported by \"\u0000virtual:#virtual-@intervalai/sb\".",
      "details": {
        "message": "Failed to analyze Mastra application: \u0000virtual:#virtual-@intervalai/sb (1:9): \"CustomerDao\" is not exported by \"../../packages/supabaseDAO/dist/index.js\", imported by \"\u0000virtual:#virtual-@intervalai/sb\".",
        "domain": "DEPLOYER",
        "category": "SYSTEM",
        "details": {}
      },
      "code": "DEPLOYER_BUNDLER_ANALYZE_FAILED"
    }
```

I was able to trace the error to the following section of code:

```
  const bundler = await rollup({
    logLevel: "silent",
    input: Array.from(virtualDependencies.entries()).reduce(
      (acc, [dep, virtualDep]) => {
        acc[virtualDep.name] = `#virtual-${dep}`;
        return acc;
      },
      {}
    ),
    external: externals,
    treeshake: "smallest",
    plugins: getInputPlugins2(virtualDependencies, {
      transpilePackages: packagesToTranspile,
      workspaceMap,
      bundlerOptions,
      rootDir
    })
  });
```

And editing this to remove the '#virtual-' prefix from my workspace package fixed the build error:

```
input: Array.from(virtualDependencies.entries()).reduce(
      (acc, [dep, virtualDep]) => {
        if(virtualDep.name.includes('ai-sb')){
            console.log('virtualDep', virtualDep)
            acc[virtualDep.name] = dep;
        }else{
            acc[virtualDep.name] = `#virtual-${dep}`;
        }
        return acc;
      }
```

I have honestly no idea why this fixed my issue. I just noticed it looked odd and tried switching it. As you may be able to tell from this comment, I really do not know how to be helpful here. I am very new to 'contributing.' (If I should submit this elsewhere please lmk)

**Comment by LekoArts** [comment]
@thereis We fixed that Windows issue (unrelated to workspaces), did you try it again in recent versions?

@AarooneyFarr Thanks for the comment and trying to help, appreciate it! A minimal reproduction would be very helpful since the code path you changed will need to stay.

I'm going through all reproductions in this thread currently (top to bottom and filling out a spreadsheet) and so far `dev` and `build` works on them. We know that `start` then most often doesn't work. We're working on that, first PR for that is in: https://github.com/mastra-ai/mastra/pull/8653

**Comment by AarooneyFarr** [comment]
@LekoArts sounds good! I have never made one of these before, so lmk if I have done something wrong.

https://github.com/AarooneyFarr/mastra-monorepo-reproduction

Edit: I've just read the instructions above. In order to reproduce the error, you should be able to just run ```npm i``` from the root, and then ```npm run build``` from the supabaseDAO package and then the interval mastra directory

**Comment by LekoArts** [comment]
@AarooneyFarr I opened a PR against your reproduction that made it work for me locally: https://github.com/AarooneyFarr/mastra-monorepo-reproduction/pull/1 - dev, build, and start works for me.

The main thing I changed was adjusting the `packages/supabaseDAO` package since that required a build step. With the work done throughout this issue that's what we want to make obsolete and it seems to work. Also settings the correct `exports` map.

@cian I tried your reproduction from https://github.com/mastra-ai/mastra/issues/6852#issuecomment-3301982072 on latest `alpha` and works for me. Can you try again? I did change the `__dirname` to an ESM variant though.

**Comment by cian** [comment]
Thanks @LekoArts  - I can confirm my reproduction from above does build on `@mastra/core@0.21.0-alpha.0`.

However, I still cannot write:
`transpilePackages: ['@acme/ai-tools', '@acme/shared']`.

It fails with:
`ERROR [...] (Mastra CLI): ../../packages/shared/src/time.ts (3:5): Expected ';', '}' or <eof> (Note that you need plugins to import files that are not JavaScript)`

I must list each submodule (i.e. `@acme/shared/time`) not just the package it's contained in.

Did you get this part to work somehow? No worries if not, if this is the intended behavior for sub-modules then a doc update to reflect this might be sufficient.

**Comment by LekoArts** [comment]
@cian Where does it fail? Do you mean in the reproduction you linked or somewhere else? Because the one you linked works for me and it uses subpath exports in `packages/ai-tools/src/tools/weather-tool.ts`. Manually specifying the `transpilePackages` for workspace packages is also not necessary anymore 👍

**Comment by cian** [comment]
@LekoArts - very good point. If I remove the `transpilePackages` section altogether it now just works. I think you can consider my specific issue fully resolved. Thanks again!

**Comment by AarooneyFarr** [comment]
For anyone else who may have experienced the same issue as I have described above, it would seem that adjusting my shared packages to have ```"type": "module"``` in the **package.json**, as suggested by @LekoArts was the fix

**Comment by JoeRoddy** [comment]
Sorry guys, could someone tell me the correct versions / alpha versions for each package to make sure I'm testing with the correct configuration?

Or if there is a shell command I can run myself to find the appropriate alphas?

Is it just `@mastra/core@0.21.0-alpha.0`? Does the `mastra` cli package version not matter?

**Comment by AarooneyFarr** [comment]
@JoeRoddy The PR @LekoArts made against my repo has all the right versions if you would like to look at it.

https://github.com/AarooneyFarr/mastra-monorepo-reproduction/pull/1

**Comment by JoeRoddy** [comment]
Feel free to ignore, bc this may be the same issue discussed earlier by @tomaswitek , but this is a rough approximation to the setup of our org's real app, with essentially the same error:

https://github.com/JoeRoddy/mastra-monorepo-issue-repro

Edit:
Looks like Leko addressed this [here](https://github.com/mastra-ai/mastra/issues/6852#issuecomment-3236918994), missed it when i went through the comments originally.

> For now, you can workaround it by adding the dependency to the project that contains Mastra.

Adding all the deps to the package that mastra is in did fix it.  Annoying, but it works!  Sorry for spam all.

**Comment by cian** [comment]
I hit an interesting issue this morning, I have a workspace import like this:
`import { serverSideOnlyDbUtility } from "@our-monorepo/internalUtils/dbActions.node";

We use the `.node` convention alongside webpack in a next.js app to prevent accidental import of server-side code in any webapps.

This inadvertently triggered the `!id.endsWith('.node')` [here](https://github.com/mastra-ai/mastra/blob/959c6e9896e5edcfd99d03c1661baadb84a4842b/packages/deployer/src/build/analyze/bundleExternals.ts#L214), resulting in a rather misleading message:

```
We found a binary dependency in your bundle. Please add `@our-monorepo/anotherPackage` to your externals.
  
export const mastra = new Mastra({
  bundler: {
    externals: ["@our-monorepo/anotherPackage"],
  }
})
```

Once I ran `mastra dev` in a debugger I could immediately see what was going on, and adjust the import statement above to not have `.node` in it. I didn't want to propose a change to the actual bundler behavior, but I have opened a tiny PR which does improve this error message a little to make it more descriptive: https://github.com/mastra-ai/mastra/pull/9056

**Comment by LekoArts** [comment]
@cian I had troubles reproducing it because Rollup didn't really like a `.node` file ending so I'm assuming you must have some custom resolvers for webpack to allow for this. We can merge the PR tho 👍 

---

I've gone through all reproductions again with the latest `alpha` versions and they all work. We'll release a stable version this week that then contains the last couple of fixes I did.

The plan is to close this mega issue at the end of the week unless some major bug comes along - because I'd consider the monorepo support to be much better (especially for the usual use cases)! Thanks y'all for helping out with reproductions ❤️ 

Afterwards you can open a bug report as usual and we'll take a look.

**Comment by psychomet** [comment]
i have nx monorepo:

npx mastra build --dir apps/mastra/src
WARN [2025-12-04 09:38:44.786 +0330] (Mastra CLI): Invalid Mastra config. Please make sure that your entry file looks like this:
export const mastra = new Mastra({
  // your options
})
  
If you think your configuration is valid, please open an issue.
INFO [2025-12-04 09:38:44.809 +0330] (Mastra CLI): Analyzing dependencies...
INFO [2025-12-04 09:38:45.901 +0330] (Mastra CLI): Optimizing dependencies...
TypeError: Invalid module "@bigi-shop-util-config" is not a valid package name imported from C:\Users\Psychomet\Projects\aiforge
    at __node_internal_ (file:///C:/Users/Psychomet/Projects/aiforge/node_modules/mlly/dist/index.mjs:469:11)
    at new NodeError (file:///C:/Users/Psychomet/Projects/aiforge/node_modules/mlly/dist/index.mjs:413:5)
    at parsePackageName (file:///C:/Users/Psychomet/Projects/aiforge/node_modules/mlly/dist/index.mjs:1783:11)
    at packageResolve (file:///C:/Users/Psychomet/Projects/aiforge/node_modules/mlly/dist/index.mjs:1807:51)
    at moduleResolve (file:///C:/Users/Psychomet/Projects/aiforge/node_modules/mlly/dist/index.mjs:1953:18)
    at _tryModuleResolve (file:///C:/Users/Psychomet/Projects/aiforge/node_modules/mlly/dist/index.mjs:2022:12)
    at _resolve (file:///C:/Users/Psychomet/Projects/aiforge/node_modules/mlly/dist/index.mjs:2077:16)
    at resolveSync (file:///C:/Users/Psychomet/Projects/aiforge/node_modules/mlly/dist/index.mjs:2110:10)
    at resolvePathSync (file:///C:/Users/Psychomet/Projects/aiforge/node_modules/mlly/dist/index.mjs:2120:24)
    at _resolve (file:///C:/Users/Psychomet/Projects/aiforge/node_modules/local-pkg/dist/index.mjs:80:22)
    at resolvePackage (file:///C:/Users/Psychomet/Projects/aiforge/node_modules/local-pkg/dist/index.mjs:133:12)
    at getPackageJsonPath (file:///C:/Users/Psychomet/Projects/aiforge/node_modules/local-pkg/dist/index.mjs:104:17)
    at file:///C:/Users/Psychomet/Projects/aiforge/node_modules/local-pkg/dist/index.mjs:114:27
    at Generator.next (<anonymous>)
    at iterateAsync (file:///C:/Users/Psychomet/Projects/aiforge/node_modules/quansync/dist/index.mjs:63:27)
    at async (file:///C:/Users/Psychomet/Projects/aiforge/node_modules/quansync/dist/index.mjs:77:14)
    at iter.then (file:///C:/Users/Psychomet/Projects/aiforge/node_modules/quansync/dist/index.mjs:23:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  code: 'ERR_INVALID_MODULE_SPECIFIER'
}
INFO [2025-12-04 09:38:51.800 +0330] (Mastra CLI): Bundling Mastra application
WARN [2025-12-04 09:38:52.234 +0330] (Mastra CLI): Circular dependency found:
        .mastra/.build/@bigi-shop-util-config.mjs -> .mastra/.build/@bigi-shop-util-config.mjs
ERROR [2025-12-04 09:38:52.304 +0330] (Mastra CLI): Failed during bundler bundle stage: "mastra" cannot be exported from ".mastra/.build/@bigi-shop-util-config.mjs" as it is a reexport that references itself.
    domain: "DEPLOYER"
    category: "SYSTEM"
    details: {}

**Comment by LekoArts** [comment]
@psychomet @chanmathew Please open separate issues that include minimal reproductions, this way we can track it better. This mega issue served its purpose at the time but now it's not accurate anymore since `@beta` is the latest at the moment for example. You also no longer need to manually define the `transpilePackages` option, it happens automatically.
