### ISSUE TITLE
[DISCORD:1420847587052752896] turborepo local package dependencies cascading?

### ISSUE THREAD

**Issue by wardpeet** [mastra-ai/mastra#8218]
This issue was created from Discord post: https://discord.com/channels/1309558646228779139/1420847587052752896

after upgrading some mastra packages I now started getting this error:
```
◐ Preparing development environment...
✓ Initial bundle complete
◇ Starting Mastra dev server...

node:internal/modules/run_main:122
    triggerUncaughtException(
    ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@aws-sdk/client-s3' imported from /Users/amosbastian/Development/reel/packages/worker-core/node_modules/.cache/@autovirality-worker-core-workflow.mjs
```

basically my main ap has `worker-core` a  dependency, which is a local package, and it that package has a depdency to another local package `cloudflare` that has `@aws-sdk/client-s3` as a dependency... not sure what is going on here all of a sudden. I build everything with tsc

**Comment by amosbastian** [comment]
I just upgraded to the latest version and it's still persisting unfortunately

**Comment by wardpeet** [comment]
Fixed by https://github.com/mastra-ai/mastra/pull/8353, will do an alpha today.

**Comment by amosbastian** [comment]
I tried `"@mastra/core": "0.20.0-alpha.0"` etc. and it's not fixed there

You can try running `pnpm dev` here: https://github.com/amosbastian/mastra-reproduction

**Comment by wardpeet** [comment]
@amosbastian we tested it and it worked, the only issue we saw was that in `apps/worker/src/mastra/index.ts` your import for the myWorkflow should have been `import { myWorkflow } from "@acme/worker-core/workflow";`

**Comment by amosbastian** [comment]
@wardpeet Sorry about that, that indeed fixed that issue, but I managed to reproduce my actual problem again by moving some code into a shared folder and then importing that in my agent or workflow which results in the error:
```
pnpm dev

> @acme/worker@ dev /Users/amosbastian/Development/mastra-build/apps/worker
> mastra dev

◐ Preparing development environment...
✓ Initial bundle complete
◇ Starting Mastra dev server...

node:internal/modules/run_main:122
    triggerUncaughtException(
    ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'drizzle-orm' imported from /Users/amosbastian/Development/mastra-build/apps/worker/.mastra/.build/test.mjs
Did you mean to import "drizzle-orm/index.cjs"?
    at Object.getPackageJSONURL (node:internal/modules/package_json_reader:268:9)
    at packageResolve (node:internal/modules/esm/resolve:768:81)
    at moduleResolve (node:internal/modules/esm/resolve:854:18)
    at defaultResolve (node:internal/modules/esm/resolve:984:11)
    at nextResolve (node:internal/modules/esm/hooks:748:28)
    at resolve (file:///Users/amosbastian/Development/mastra-build/node_modules/.pnpm/mastra@0.15.1_@mastra+core@0.20.2_openapi-types@12.1.3_react@19.1.1_zod@4.1.12__@opente_bb5b6f80fe1f3d9ab4c01b8221089416/node_modules/mastra/dist/commands/dev/telemetry-resolver.js:4:12)
    at nextResolve (node:internal/modules/esm/hooks:748:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:240:30)
    at handleMessage (node:internal/modules/esm/worker:199:24)
    at checkForMessages (node:internal/modules/esm/worker:141:28) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

maybe this is expected, but then I'm not sure what to do about it (add everything to `bundler.externals`?)
